//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tel_satis_otomasyonu_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciID { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciSifre { get; set; }
    }
}
