//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tel_satis_otomasyonu_v1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelsatDBEntities1 : DbContext
    {
        public TelsatDBEntities1()
            : base("name=TelsatDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fatura> fatura { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urunMik> urunMik { get; set; }
        public virtual DbSet<urunTL> urunTL { get; set; }
        public virtual DbSet<musteri_fatura_View> musteri_fatura_View { get; set; }
        public virtual DbSet<satislar_musteri_fatura> satislar_musteri_fatura { get; set; }
    }
}
