//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tel_satis_otomasyonu_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunMik
    {
        public int urunlermikID { get; set; }
        public Nullable<int> telorguM { get; set; }
        public Nullable<int> betondirekA { get; set; }
        public Nullable<int> payandadirekA { get; set; }
        public Nullable<int> gerdirmetelM { get; set; }
        public Nullable<int> dikenlitelM { get; set; }
        public Nullable<int> betontasM3 { get; set; }
        public Nullable<int> baglamatelM { get; set; }
        public Nullable<int> iscilikM { get; set; }
    }
}
