//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tel_satis_otomasyonu_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunTL()
        {
            this.fatura = new HashSet<fatura>();
        }
    
        public int urunfiyatID { get; set; }
        public Nullable<int> telorguTL { get; set; }
        public Nullable<int> betondirekTL { get; set; }
        public Nullable<int> payandadirekTL { get; set; }
        public Nullable<int> gerdirmetelTL { get; set; }
        public Nullable<int> dikenlitelTL { get; set; }
        public Nullable<int> betontasTL { get; set; }
        public Nullable<int> baglamatelTL { get; set; }
        public Nullable<int> iscilikTL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fatura> fatura { get; set; }
    }
}
